export const metadata = {
    title: 'Profil utilisateur',
    description: 'Generated by create next app',
  }
  import SideMenu from "./components/SideMenu"
  
  export default function BasicGroupLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div className="flex items-center justify-center w-full h-screen bg-gray-100">
           <SideMenu/>
            <div className="w-[80%] flex justify-center overflow-x-auto items-center  h-full">
                {children}
            </div>
        </div>
    )}