import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToastProvider } from '@/contexts/ToastContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='h-screen w-full bg-white  text-gray-700' suppressHydrationWarning={true} lang="en">
      <body className={inter.className}>
        {/* <Navbar/> */}
        <div>
          <ToastProvider>
          {children}
          </ToastProvider>
        </div>
      </body>
    </html>
  )
}
