export const metadata = {
  title: 'Basic Group',
  description: 'Generated by create next app',
}

export default function BasicGroupLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className="bg-gray-100 h-screen w-full flex justify-center items-center md:px-12 px-4">{children}</div>
  )
}