export const metadata = {
    title: 'Profil utilisateur',
    description: 'Generated by create next app',
  }
  import SideMenu from "./components/SideMenu"
  
  export default function BasicGroupLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div className="bg-gray-100 h-screen w-full flex justify-center items-center">
           <SideMenu/>
            <div className="w-[80%] bg-white h-full">
                {children}
            </div>

        </div>
    )}