export const metadata = {
    title: 'Profil utilisateur',
    description: 'Generated by create next app',
  }
  
  export default function BasicGroupLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div className="bg-gray-100 h-screen w-full flex justify-center items-center">
            <div className="w-[20%] my-3 mx-6 h-full">
                <h1 className="font-bold w-full text-blue-600 text-2xl">Art.cd</h1>
            </div>
            <div className="w-[80%] bg-white h-full">
                {children}
            </div>

        </div>
    )}